server:
  port: 3344

spring:
  application:
    name: config3344
####################################################################  进入组件
######################  config组件
  cloud:
    config:
      server:
        git:
#          uri: git@github.com:zangtie/springcloud-config.git # 新建的 repository 的对应 git 地址。这样 Config Server 端就知道从哪获取配置信息了
          uri: https://github.com/zangtie/springcloud-config.git # 新建的 repository 的对应 git 地址。这样 Config Server 端就知道从哪获取配置信息了
          # 搜索目录
          search-paths:
            - springcloud-config
      label: master  # 读取分支

#  http://localhost:3344/application-test.yml 可以访问到gitbub上面的dev 或者test的配置
#  http://localhost:3344/application-dev.yml

######################   Eureka组件
#客户端注册进Eureka服务列表里
eureka:
  client:
    service-url:
      #      default-zone: http://eureka01:7001/eureka/  #巨坑，default-zone这个写法不对，正确的应该是defaultZone
      #       defaultZone: http://eureka01:7001/eureka/   #巨坑 C:\Windows\System32\drivers\etc目录下hosts文件修改127.0.0.1原对应localhost为eureka01
      defaultZone: http://eureka01:7001/eureka/,http://eureka02:7002/eureka/
  instance:
    instance-id: config3344  # 注册中心显示服务名字
    prefer-ip-address: true # 注册中心显示服务地址 默认false是不显示的

####################################################################  进入组件
